version: '3.8'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - npm_data:/data
      - npm_certs:/etc/letsencrypt
      - /var/log/nginx:/data/logs/
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - stack.env
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html:z
      - nextcloud_data:/var/www/html/data:z
    env_file:
      - stack.env      
    environment:
      - APACHE_DISABLE_REWRITE_IP=1 # Behind proxy
      - TRUSTED_PROXIES=npm
      - PUID=1000
      - PGID=1000
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    restart: unless-stopped
    depends_on:
      - npm
      - db
      - redis
  cron:
    image: nextcloud:apache
    restart: unless-stopped
    container_name: cron
    volumes:
      - nextcloud:/var/www/html:z
      - nextcloud_data:/var/www/html/data:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log/nginx/:/var/log/nginx/
      - /etc/promtail/:/etc/promtail/:ro
    command: -config.file=/etc/promtail/config.yml
volumes:
  npm_data:
  npm_certs:
  db:
  nextcloud:
  nextcloud_data:
